export { default as AfterLogin } from './afterLogin/AfterLogin'
export { default as About } from './about/About'
export { default as Home } from './home/Home'
export { default as PageNotAuthorized } from './pageNotAuthorized/PageNotAuthorized'
export { default as PageNotFound } from './pageNotFound/PageNotFound'